# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Risor < Formula
  desc "An embedded scripting language for Go projects"
  homepage "https://github.com/risor-io/risor"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/risor-io/risor/releases/download/v0.8.0/risor_Darwin_arm64.tar.gz"
      sha256 "dda2e25f0a243a040638184ea668e995a20015eed46efc289ca88cbf17fefc2f"

      def install
        bin.install "risor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/risor-io/risor/releases/download/v0.8.0/risor_Darwin_x86_64.tar.gz"
      sha256 "a862b6d4ded6bf4890aaf832dc4541ed0a0fc1573774ccd6a7b03ff2473dc844"

      def install
        bin.install "risor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/risor-io/risor/releases/download/v0.8.0/risor_Linux_arm64.tar.gz"
      sha256 "1581e5f2d4361c892fc7b37638aec0d1b6e9c7b6ae7248c183dd50de4643dc87"

      def install
        bin.install "risor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/risor-io/risor/releases/download/v0.8.0/risor_Linux_x86_64.tar.gz"
      sha256 "e4ef40cfedc2ec3f936c40863ae1df4873e0b3c87e239358e833b51e5121091b"

      def install
        bin.install "risor"
      end
    end
  end
end
