# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Risor < Formula
  desc "An embedded scripting language for Go projects"
  homepage "https://github.com/risor-io/risor"
  version "1.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/risor-io/risor/releases/download/v1.8.0/risor_Darwin_x86_64.tar.gz"
      sha256 "1cd56feb11f074b8eed10135c0edb743e657237799715d62ddf7522c3eba59c3"

      def install
        bin.install "risor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/risor-io/risor/releases/download/v1.8.0/risor_Darwin_arm64.tar.gz"
      sha256 "fbc82f5bf0799cadf0aa89b7c58affd09266eff101317773b0f0b3783fa391d3"

      def install
        bin.install "risor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/risor-io/risor/releases/download/v1.8.0/risor_Linux_x86_64.tar.gz"
        sha256 "ca4c8519e18a9f4ceb639da5a2cd3d655b411addfb532a02ff2a63e65311aa77"

        def install
          bin.install "risor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/risor-io/risor/releases/download/v1.8.0/risor_Linux_arm64.tar.gz"
        sha256 "c653ce009d3d780dace3c7d574103242a192a12338b1b967145ed90d2956d8b2"

        def install
          bin.install "risor"
        end
      end
    end
  end
end
